-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 17:00:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema func_storage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema func_storage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `func_storage` DEFAULT CHARACTER SET utf8 ;
USE `func_storage` ;

-- -----------------------------------------------------
-- Table `func_storage`.`func`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `func_storage`.`func` (
  `idfunc` INT NOT NULL AUTO_INCREMENT,
  `funccontent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfunc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `func_storage`.`roots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `func_storage`.`roots` (
  `idroots` INT NOT NULL AUTO_INCREMENT,
  `rootscontent` DOUBLE NOT NULL,
  PRIMARY KEY (`idroots`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `func_storage`.`pairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `func_storage`.`pairs` (
  `idpairs` INT NOT NULL AUTO_INCREMENT,
  `idroots` INT NOT NULL,
  `idfunc` INT NOT NULL,
  PRIMARY KEY (`idpairs`),
  INDEX `fk_pairs_1_idx` (`idfunc` ASC) VISIBLE,
  INDEX `roo_idx` (`idroots` ASC) VISIBLE,
  CONSTRAINT `fun`
    FOREIGN KEY (`idfunc`)
    REFERENCES `func_storage`.`func` (`idfunc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `roo`
    FOREIGN KEY (`idroots`)
    REFERENCES `func_storage`.`roots` (`idroots`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
